//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} locals).
        /// </summary>
        internal static string CallStackFrameFormat {
            get {
                return ResourceManager.GetString("CallStackFrameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user-defined class cannot implement IScriptObject interface..
        /// </summary>
        internal static string CustomClassCannotImplementScriptInterface {
            get {
                return ResourceManager.GetString("CustomClassCannotImplementScriptInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Entry Point&gt;.
        /// </summary>
        internal static string EntryPointFrameID {
            get {
                return ResourceManager.GetString("EntryPointFrameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; doesn&apos;t contain script implementation..
        /// </summary>
        internal static string InvalidScriptAssembly {
            get {
                return ResourceManager.GetString("InvalidScriptAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring is not enabled..
        /// </summary>
        internal static string MonitoringNotEnabled {
            get {
                return ResourceManager.GetString("MonitoringNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime slot is not available at the current call stack frame. Possible, it is out of lexical scope..
        /// </summary>
        internal static string SlotIsOutOfScope {
            get {
                return ResourceManager.GetString("SlotIsOutOfScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An asynchronous object is in running state..
        /// </summary>
        internal static string StillRunning {
            get {
                return ResourceManager.GetString("StillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract binding: {0}.
        /// </summary>
        internal static string StorageContract {
            get {
                return ResourceManager.GetString("StorageContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        internal static string StorageName {
            get {
                return ResourceManager.GetString("StorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantics: {0}.
        /// </summary>
        internal static string StorageSemantics {
            get {
                return ResourceManager.GetString("StorageSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value: {0}.
        /// </summary>
        internal static string StorageValue {
            get {
                return ResourceManager.GetString("StorageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;VALUE CANNOT BE DISPLAYED&gt;.
        /// </summary>
        internal static string UnprintableValue {
            get {
                return ResourceManager.GetString("UnprintableValue", resourceCulture);
            }
        }
    }
}
