//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicScript {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicScript.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual arguments are not satisifed to the action parameters..
        /// </summary>
        internal static string ArgumentMistmatch {
            get {
                return ResourceManager.GetString("ArgumentMistmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant cannot be overwritten after its declaration..
        /// </summary>
        internal static string AttemptsToWriteConstant {
            get {
                return ResourceManager.GetString("AttemptsToWriteConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object &apos;{0}&apos; is not satisfied to the &apos;{1}&apos; contract..
        /// </summary>
        internal static string ContractBinding {
            get {
                return ResourceManager.GetString("ContractBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object used for contract binding is not a contract..
        /// </summary>
        internal static string ContractExpected {
            get {
                return ResourceManager.GetString("ContractExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate variable &apos;{0}&apos; declaration, object slot or action parameter..
        /// </summary>
        internal static string DuplicateIdentifier {
            get {
                return ResourceManager.GetString("DuplicateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array is empty and cannot be used for set contract..
        /// </summary>
        internal static string EArrayisEmptyForSet {
            get {
                return ResourceManager.GetString("EArrayisEmptyForSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified object is not a collection..
        /// </summary>
        internal static string ECollectionExpected {
            get {
                return ResourceManager.GetString("ECollectionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of collection is reached..
        /// </summary>
        internal static string EndOfCollection {
            get {
                return ResourceManager.GetString("EndOfCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of multiline comment expected..
        /// </summary>
        internal static string EndOfCommentExpected {
            get {
                return ResourceManager.GetString("EndOfCommentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown interpreter error..
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Column {1}, Line {2}..
        /// </summary>
        internal static string FmtErrorMessage {
            get {
                return ResourceManager.GetString("FmtErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier name expected..
        /// </summary>
        internal static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is incompleted..
        /// </summary>
        internal static string IncompletedExpression {
            get {
                return ResourceManager.GetString("IncompletedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompleted statement or expression..
        /// </summary>
        internal static string IncorrectCodeDom {
            get {
                return ResourceManager.GetString("IncorrectCodeDom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression term &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidExpressionTerm {
            get {
                return ResourceManager.GetString("InvalidExpressionTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating-point literal has invalid format..
        /// </summary>
        internal static string InvalidFloatingPointNumberFormat {
            get {
                return ResourceManager.GetString("InvalidFloatingPointNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operator or expression after groupby keyword expected..
        /// </summary>
        internal static string InvalidLoopGrouping {
            get {
                return ResourceManager.GetString("InvalidLoopGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos; but &apos;{1}&apos; found..
        /// </summary>
        internal static string InvalidPunctuation {
            get {
                return ResourceManager.GetString("InvalidPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts to reading from unassigned variable or object slot..
        /// </summary>
        internal static string ReadingFromUnassigedSlot {
            get {
                return ResourceManager.GetString("ReadingFromUnassigedSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning from FINALLY block is not allowed..
        /// </summary>
        internal static string ReturnFormFinally {
            get {
                return ResourceManager.GetString("ReturnFormFinally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action return type expected..
        /// </summary>
        internal static string ReturnTypeOrVoidExpected {
            get {
                return ResourceManager.GetString("ReturnTypeOrVoidExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script exception is occured and produced by &apos;{0}&apos; script object..
        /// </summary>
        internal static string ScriptFault {
            get {
                return ResourceManager.GetString("ScriptFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; is not declared in the current scope..
        /// </summary>
        internal static string UndeclaredIdentifier {
            get {
                return ResourceManager.GetString("UndeclaredIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitialized constant..
        /// </summary>
        internal static string UninitializedConstant {
            get {
                return ResourceManager.GetString("UninitializedConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized character: &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownCharacter {
            get {
                return ResourceManager.GetString("UnknownCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion from &apos;{0}&apos; is not supported by DynamicScript interpreter..
        /// </summary>
        internal static string UnsupportedConversion {
            get {
                return ResourceManager.GetString("UnsupportedConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not supported for the specified operands..
        /// </summary>
        internal static string UnsupportedOperation {
            get {
                return ResourceManager.GetString("UnsupportedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary, unary or invocation operation with VOID object is not supported..
        /// </summary>
        internal static string VoidObjectDetected {
            get {
                return ResourceManager.GetString("VoidObjectDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong escape sequence..
        /// </summary>
        internal static string WrongEscapeSequence {
            get {
                return ResourceManager.GetString("WrongEscapeSequence", resourceCulture);
            }
        }
    }
}
